# Generated by Django 2.0.3 on 2018-03-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_auto_20180324_0054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('domain_name', models.CharField(max_length=256)),
                ('private_key', models.TextField(blank=True, null=True)),
                ('conf', models.TextField(blank=True, null=True)),
                ('csr', models.TextField(blank=True, null=True)),
                ('crt', models.TextField(blank=True, null=True)),
                ('intermediate', models.TextField(blank=True, null=True)),
                ('valid', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='domain',
            old_name='conf',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='private_key',
        ),
        migrations.AddField(
            model_name='domain',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
