# Generated by Django 2.0.3 on 2018-03-27 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_auto_20180324_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='domain_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.Domain'),
        ),
    ]
