# Generated by Django 2.0.3 on 2018-03-27 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0004_auto_20180327_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='domain_name',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='certificates.Domain'),
        ),
    ]
